name: CI Trigger Debug

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  debug:
    name: Debug event and environment
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Ref:   $GITHUB_REF"
          echo "SHA:   $GITHUB_SHA"
          echo "Repo:  $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
      - name: Checkout to confirm permissions
        uses: actions/checkout@v4
      - name: Done
        run: echo "CI triggered successfully on this push."
